apiVersion: apps/v1
kind: Deployment
metadata:
  name: thesaurus
  labels:
    app: thesaurus

spec:
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app: thesaurus

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: thesaurus

    spec:
      containers:
      - name: webapp
        image: infrascielo/thesaurus   # digest vem do kustomize
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 80
          name: webapp

        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
