apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# usa base comum
resources:
  - ../base

# namespace de produção
namespace: prd-delorean

# replicas de produção
replicas:
  - name: delorean-app
    count: 1

# imagem com digest (CI atualiza)
images:
  - name: infrascielo/delorean
    newName: infrascielo/delorean
    digest: sha256:8c03bf1ae0f696f8eb9f1313967e512eb01690c8dbd4b9b218beb0e74442e52b

# patches específicos de produção
patches:
  # Deployment
  - target:
      kind: Deployment
      name: delorean-app
    patch: |
      # tolerations de produção
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: app
            operator: Equal
            value: producao
            effect: NoSchedule

  # Service
  - target:
      kind: Service
      name: delorean-app-svc
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32646
