apiVersion: apps/v1
kind: Deployment
metadata:
  name: delorean-app

spec:
  template:
    spec:
      tolerations:
      - key: app
        operator: Equal
        value: producao
        effect: NoSchedule
