apiVersion: apps/v1
kind: Deployment
metadata:
  name: delorean-app

spec:
  template:
    spec:
      containers:
      - name: webapp
        envFrom:
        - configMapRef:
            name: delorean-env

      tolerations:
      - key: app
        operator: Equal
        value: producao
        effect: NoSchedule
