apiVersion: v1
kind: Secret
metadata:
  name: secrets-thesaurus
  namespace: hml-thesaurus
type: Opaque
stringData:
  TEMATRES_DB_HOST: "replace-with-db-host"
  TEMATRES_DB_NAME: "replace-with-db-name"
  TEMATRES_DB_USER: "replace-with-db-user"
  TEMATRES_DB_PASSWORD: "replace-with-db-password"
