apiVersion: v1
kind: Service
metadata:
  name: delorean-app-svc
  labels:
    app: delorean-app

spec:
  type: NodePort

  ports:
    - name: webapp
      port: 6543
      targetPort: 6543
      protocol: TCP

  selector:
    app: delorean-app
