apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: qa1-scielo-br

namePrefix: qa1-

replicas:
  - name: scielo-app
    count: 1

images:
  - name: infrascielo/opac_5
    newName: infrascielo/opac_5
    digest: sha256:21cc728ec4f0653cfe6903437d2bf838fbe373563c4179adf4e96f963b51d4f3

# JSON patch só para Service
patches:
  - target:
      kind: Service
      name: scielo-app-svc
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32642

# Strategic merge para Deployment
patchesStrategicMerge:
  - patch-deployment.yaml
