apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: qa1-scielo-br

namePrefix: qa1-

replicas:
  - name: scielo-app
    count: 1

images:
  - name: infrascielo/opac_5
    newName: infrascielo/opac_5
    digest: sha256:433dbb00c38cc05ad3d84f46f08b0ad96c805b3cec6aee6f1aebf378a0c7c6f6

# JSON patch só para Service
patches:
  - target:
      kind: Service
      name: scielo-app-svc
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32642

# Strategic merge para Deployment
patchesStrategicMerge:
  - patch-deployment.yaml
