apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: qa1-scielo-br

namePrefix: qa1-

replicas:
  - name: scielo-app
    count: 1

images:
  - name: infrascielo/opac_5
    newName: infrascielo/opac_5
    digest: sha256:3f6c188d6ffe51d423fd357a09d2906a7ce900de72941e5734f821495f07688d

# JSON patch só para Service
patches:
  - target:
      kind: Service
      name: scielo-app-svc
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32642

# Strategic merge para Deployment
patchesStrategicMerge:
  - patch-deployment.yaml
