apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: hml-delorean

replicas:
  - name: delorean-app
    count: 1

images:
  - name: infrascielo/delorean
    newName: infrascielo/delorean
    digest: sha256:df7d4d53e7f617cdee0faddf8e1064587cf206ef553187f58daebf35325f13a3

# JSON patch só para Service
patches:
  - target:
      kind: Service
      name: delorean-app-svc
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32643

# Strategic merge para Deployment
patchesStrategicMerge:
  - patch-deployment.yaml
