apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: hml-delorean

replicas:
  - name: delorean-app
    count: 1

images:
  - name: infrascielo/delorean
    newName: infrascielo/delorean
    digest: sha256:d48c452388b4a08de750ed59e0d955e914cb0f41759657079b67b7d4a130bc62

# JSON patch só para Service
patches:
  - target:
      kind: Service
      name: delorean-app-svc
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32643

# Strategic merge para Deployment
patchesStrategicMerge:
  - patch-deployment.yaml
