apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: hml-delorean

replicas:
  - name: delorean-app
    count: 1

images:
  - name: infrascielo/delorean
    newName: infrascielo/delorean
    digest: sha256:28c6fc0c922947f8f646519605fdf6168960b7bb87047b70366dfd58546a1097

# JSON patch só para Service
patches:
  - target:
      kind: Service
      name: delorean-app-svc
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32645

# Strategic merge para Deployment
patchesStrategicMerge:
  - patch-deployment.yaml
